### ISSUE TITLE
Favicon is Angular Logo

### ISSUE THREAD

**Issue by pDiller** [reflectoring/infiniboard#196]
Infiniboard has no own favicon. It shows the icon from AngularJS
If you want to change it, feel free. :)

**Comment by matthiasbalke** [comment]
The official infiniboard logo should be used instead. The needed assets were generated using http://realfavicongenerator.net and are attached to this issue ([favicons.zip](https://github.com/reflectoring/infiniboard/files/842747/favicons.zip))

embedded icons like this
```html
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">
```
**acceptance criteria**

* favicon replaced
* apple touch icons replaced
* safari icon replaced
* windows tiles icon configured
