### ISSUE TITLE
https://reflectoring.io/infiniboard Page not found

### ISSUE THREAD

**Issue by pDiller** [reflectoring/infiniboard#218]
The link to Infiniboard Homepage (https://reflectoring.io/infiniboard) seems to be broken. It shows your "Page not found"-page.

**Comment by matthiasbalke** [comment]
The domain `reflectoring.io` currently has an A record configured to point to netlify: https://www.netlify.com/docs/custom-domains/

```
$ dig reflectoring.io +nostats +nocomments +nocmd

; <<>> DiG 9.9.5-3ubuntu0.16-Ubuntu <<>> reflectoring.io +nostats +nocomments +nocmd
;; global options: +cmd
;reflectoring.io.               IN      A
reflectoring.io.        3336    IN      A       104.198.14.52
```

To work with GitHub pages, it must have two A records configured to point to GitHub:
* 192.30.252.153
* 192.30.252.154

If this configuration clashes with the blog deployment, we could create an subdomain `blog` and `www` for the blog and serve the other projects via GitHub pages:
https://help.github.com/articles/setting-up-a-www-subdomain/

**Comment by matthiasbalke** [comment]
The project pages are available using http://projects.reflectoring.io/infiniboard
