### ISSUE TITLE
platform independent UML editor

### ISSUE THREAD

**Issue by matthiasbalke** [reflectoring/infiniboard#25]
Since UMLed is only available for windows, we should consider switching to an UML editor working for Windows, Mac OS X and Linux.

**Comment by matthiasbalke** [comment]
The only one I know is: [Astah Community](http://astah.net/editions/community)

**Comment by RudiKlassen** [comment]
I will port my diagramm to the Astah-Community-Version und update my Pull-Request.

**Comment by Pentadrago** [comment]
http://www.umlet.com/ also seems to be a good choice

**Comment by matthiasbalke** [comment]
My fault. Seems I found the wrong website. But we're is the download link?

**Comment by RudiKlassen** [comment]
http://www.umlet.com/changes.htm

**Comment by matthiasbalke** [comment]
Lets use UMLet then.
