### ISSUE TITLE
check UrlRewriteFilter configuration

### ISSUE THREAD

**Issue by Pentadrago** [reflectoring/infiniboard#49]
UrlRewriteFilter doesn't seem to behave correctly, e.g. /dashboards or /widgets return the SpringBoot error page.

**Comment by matthiasbalke** [comment]
The filter seems to be not working when running quartermaster from jar/docker, while it is working when using `bootRun`.

**Comment by matthiasbalke** [comment]
There is a [issue](https://github.com/spring-projects/spring-boot/issues/3627#issuecomment-190862326) in the spring-boot issue tracker regarding this bug. Seems that there is a problem with the resource loading in Tomcat 8.

**Comment by matthiasbalke** [comment]
We will stick to HashLocationStrategy as long as there are no problems with it.
