### ISSUE TITLE
update spring boot version

### ISSUE THREAD

**Issue by matthiasbalke** [reflectoring/infiniboard#50]
update spring boot to current stable version: 1.3.6.RELEASE

**Comment by acetous** [comment]
Check if Spring Data Rest exposes all repositories over HTTP. You can disable this in Spring Boot version >1.4.1 via the [RepositoryDetectionStrategy#ANNOTATION](http://docs.spring.io/spring-data/rest/docs/current/reference/html/#_which_repositories_get_exposed_by_defaults)
