### ISSUE TITLE
unit testing exception cases

### ISSUE THREAD

**Issue by matthiasbalke** [reflectoring/infiniboard#67]
I just realized that we are checking the messages of exceptions in unit tests (e.g. [](https://github.com/reflectoring/infiniboard/blob/master/harvester/src/test/java/com/github/reflectoring/infiniboard/harvester/scheduling/SchedulingServiceTest.java#L58)). IMO we shouldn't check for exception messages. Instead we should check only the exception type. If we use the same exception type for different error cases we run into problems as these cases can only be detected by parsing the exception messages, which is a bad style.

So instead of using `expectedException.expectedMessage("message")` we should use `expectedException.expect(IllegalArgumentException.class)`.

**Comment by Pentadrago** [comment]
The scheduling service was changed to throw different exceptions defined in the harvester module. The unit tests behave accordingly.
